services:
  deteccao-ia:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - PORT=8080
    restart: unless-stopped

