app = "deteccaoia"

kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "15s"

[experimental]
  auto_rollback = true
  ipv6 = false
  auto_stop_machines = true
  auto_start_machines = false