name: Desligar App

on:
  schedule:
    - cron: '0 23 * * *' # 20:00 BRT (UTC+3)
  workflow_dispatch:

jobs:
  desligar:
    runs-on: ubuntu-latest
    steps:
      - name: Desligar app no Fly.io
        run: fly scale count 0
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
